export const PROJECT0550_CONTROL_OBJECTS = [
  {
    id: "CTRL-PAGA-001",
    object: "PAGA Sound Coverage Study",
    system: "TEL-PAGA",
    source: "0550 PAGA source chain; required RPT-0005 proof object",
    applicability: "ACTIVE",
    driver: "Ambient noise + geometry + coverage criteria + layout/topology inputs",
    proof: "RPT-0005 / supporting CAL-SDY objects",
    quantity: "Final speaker / beacon quantity = TBC",
    workload: "Study + engineering + review + controlled report issue",
    owner: "TBC — bind from 0550 responsibility source",
    treatment: "Current budgetary line exists; final treatment waits for engineering closure",
    state: "BLOCKED BY INPUTS",
    next: "Close ambient noise, geometry, APF cable schedule, loop topology, cable loss, final coverage and UPS calculation.",
    control: {
      sourceEvidence: { state: "FACT", refs: ["PHI","BOD","SPE","DWG","MR"] },
      requirement: { state: "FACT", value: "Provide compliant PAGA coverage / alarm performance for required locations." },
      fundamentalNeed: { state: "FACT", value: "People must receive intelligible / effective public address and alarm indication." },
      constraints: [
        { id:"PAGA-C-01", type:"TECHNICAL", state:"OPEN", value:"Ambient noise / geometry / coverage inputs not fully controlled." },
        { id:"PAGA-C-02", type:"TECHNICAL", state:"OPEN", value:"Cable / loop loss and topology not fully controlled." },
        { id:"PAGA-C-03", type:"NON_TECHNICAL", state:"OPEN", value:"Responsibility / acceptance boundary remains to be bound to 0550 source." }
      ],
      interfaceContext: { state:"PARTIAL" },
      engineeringInputs: { state:"PARTIAL" },
      calStudyRpt: { required:true, state:"OPEN", objects:["RPT-0005","PAGA-CAL-COVER-001","PAGA-CAL-AMP-001","PAGA-CAL-LOSS-001","PAGA-CAL-UPS-001","PAGA-SDY-IF-001"] },
      proof: { required:true, state:"OPEN", objects:["coverage acceptance","loading acceptance","loss/topology acceptance","UPS/autonomy acceptance","interface verification"] },
      architecture: { state:"PRELIMINARY" },
      physicalObjects: { state:"PRELIMINARY", classes:["speaker","beacon","amplifier","cable","I/O","accessories"] },
      quantityDriver: { state:"PARTIAL", value:"coverage + load + topology + loss + redundancy" },
      requiredMto: { state:"TBC", quantity:null },
      bulk: { state:"WORKING" },
      vendorOffer: { state:"PARTIAL", quantity:null },
      reconciliation: { state:"OPEN", disposition:null },
      workResource: { state:"WORKING" },
      documentQa: { state:"WORKING" },
      fatIfat: { state:"WORKING" },
      logisticsRegulatory: { state:"OPEN" },
      siteReadiness: { state:"OPEN" },
      installPrecom: { state:"OPEN" },
      satCommissioning: { state:"OPEN" },
      handoverWarranty: { state:"OPEN" },
      costScheduleRisk: { state:"WORKING", costValue:1509940.27, currency:"USD", costBasis:"BUDGETARY / CURRENT QUOTE + WORKING BULK" },
      commercialTreatment: { state:"WORKING", priceLine:"A1-05" },
      release: { state:"OPEN", reason:"Required proof, final required MTO, bulk, lifecycle completion and final commercial treatment remain open." }
    }
  },
  {
    id: "CTRL-VDRL-001",
    object: "VDRL / Document Production",
    system: "COMMON",
    source: "0550 MR / document obligations / project document-control requirements",
    applicability: "ACTIVE",
    driver: "Q_issue + Q_content + review/revision/final-issue lifecycle",
    proof: "Source row + evidence + revision history",
    quantity: "Q_issue / Q_content = TBC by deliverable",
    workload: "MH_prepare + check + DC + review + revise + final issue",
    owner: "TBC per deliverable / activity",
    treatment: "Map cost once to the applicable 0550 price line",
    state: "STRUCTURE READY",
    next: "Bind issue recurrence, content quantity, review cycle and owner from current 0550 VDRL/MDDR source.",
    control: {
      sourceEvidence: { state:"FACT", refs:["MR","VDRL/MDDR obligations"] },
      requirement: { state:"FACT", value:"Produce and control required vendor/project deliverables through review and final issue." },
      fundamentalNeed: { state:"FACT", value:"Engineering evidence must be reviewable, approvable and traceable through revision." },
      constraints: [{ id:"VDRL-C-01", type:"NON_TECHNICAL", state:"OPEN", value:"Issue recurrence / review-cycle count not fully bound." }],
      interfaceContext: { state:"FACT" },
      engineeringInputs: { state:"PARTIAL" },
      proof: { required:false, state:"NOT_APPLICABLE", objects:[] },
      architecture: { state:"FACT" },
      physicalObjects: { state:"FACT", classes:["document issue","revision","review cycle","final dossier"] },
      quantityDriver: { state:"PARTIAL", value:"issue count + content count + review/revision cycles" },
      requiredMto: { state:"NOT_APPLICABLE", quantity:null },
      bulk: { state:"NOT_APPLICABLE" },
      vendorOffer: { state:"NOT_APPLICABLE", quantity:null },
      reconciliation: { state:"NOT_APPLICABLE", disposition:"N/A" },
      workResource: { state:"PARTIAL" },
      documentQa: { state:"WORKING" },
      fatIfat: { state:"NOT_APPLICABLE" },
      logisticsRegulatory: { state:"NOT_APPLICABLE" },
      siteReadiness: { state:"NOT_APPLICABLE" },
      installPrecom: { state:"NOT_APPLICABLE" },
      satCommissioning: { state:"NOT_APPLICABLE" },
      handoverWarranty: { state:"WORKING" },
      costScheduleRisk: { state:"PARTIAL", costValue:null, currency:"USD", costBasis:"MH / lifecycle model" },
      commercialTreatment: { state:"WORKING", priceLine:"B1 / common project controls" }
    }
  },
  {
    id: "CTRL-TEST-001",
    object: "FAT / IFAT / SAT / Commissioning",
    system: "COMMON",
    source: "0550 contract / technical lifecycle obligations",
    applicability: "ACTIVE / VERIFY BY SYSTEM",
    driver: "Required event × crew × duration × test scope",
    proof: "ITP / procedure / report / acceptance evidence",
    quantity: "EventKey = OPEN",
    workload: "Technical test MH + incremental event cost",
    owner: "TBC by event and responsibility",
    treatment: "Base / separate treatment must follow current 0550 commercial mapping",
    state: "EVENT BINDING OPEN",
    next: "Create EventKey and PhysicalTripKey so one real trip is not charged repeatedly across FAT/SAT/training/field work.",
    control: {
      sourceEvidence: { state:"FACT", refs:["Contract","MR/SPE lifecycle obligations"] },
      requirement: { state:"FACT", value:"Perform required acceptance / integration / commissioning events where applicable." },
      fundamentalNeed: { state:"FACT", value:"Prove supplied systems perform and integrate before acceptance." },
      constraints: [
        { id:"TEST-C-01", type:"TECHNICAL", state:"OPEN", value:"Per-system event applicability and test scope not fully bound." },
        { id:"TEST-C-02", type:"NON_TECHNICAL", state:"OPEN", value:"Crew / duration / witness / travel grouping not fully bound." }
      ],
      interfaceContext: { state:"PARTIAL" },
      engineeringInputs: { state:"PARTIAL" },
      proof: { required:true, state:"OPEN", objects:["ITP","FAT/IFAT/SAT procedure","test report"] },
      architecture: { state:"NOT_APPLICABLE" },
      physicalObjects: { state:"FACT", classes:["execution event","test scope","witness point","physical trip"] },
      quantityDriver: { state:"OPEN", value:"EventKey × crew × duration × scope" },
      requiredMto: { state:"NOT_APPLICABLE", quantity:null },
      bulk: { state:"NOT_APPLICABLE" },
      vendorOffer: { state:"NOT_APPLICABLE", quantity:null },
      reconciliation: { state:"NOT_APPLICABLE", disposition:"N/A" },
      workResource: { state:"OPEN" },
      documentQa: { state:"WORKING" },
      fatIfat: { state:"OPEN" },
      logisticsRegulatory: { state:"WORKING" },
      siteReadiness: { state:"OPEN" },
      installPrecom: { state:"OPEN" },
      satCommissioning: { state:"OPEN" },
      handoverWarranty: { state:"OPEN" },
      costScheduleRisk: { state:"PARTIAL", costValue:null, currency:"USD", costBasis:"Event / resource parametric model" },
      commercialTreatment: { state:"WORKING", priceLine:"B4 / applicable service lines" }
    }
  },
  {
    id: "CTRL-LOG-001",
    object: "Logistics / Permit / Import Responsibility",
    system: "COMMON",
    source: "0550 Contract / logistics instructions / vendor origin and delivery basis",
    applicability: "CONTEXT DRIVEN",
    driver: "Origin + delivery point + Incoterm + permit/import responsibility",
    proof: "Contract clause / vendor quote / logistics evidence",
    quantity: "Shipment / permit occurrences = TBC",
    workload: "Admin + logistics + permit/application + financing exposure where applicable",
    owner: "TBC — seller / buyer / vendor / reimbursable owner must be explicit",
    treatment: "Do not bury in miscellaneous allowance",
    state: "RESPONSIBILITY OPEN",
    next: "Bind responsibility and cost owner from 0550 sources before price freeze.",
    control: {
      sourceEvidence: { state:"FACT", refs:["0550 logistics / commercial sources"] },
      requirement: { state:"FACT", value:"Deliver, permit and import/export project goods according to governing project boundary." },
      fundamentalNeed: { state:"FACT", value:"Equipment must legally and physically reach the required handover point." },
      constraints: [
        { id:"LOG-C-01", type:"NON_TECHNICAL", state:"OPEN", value:"Importer / customs / inland responsibility not fully closed." },
        { id:"LOG-C-02", type:"NON_TECHNICAL", state:"OPEN", value:"Permit / licence / authority route is equipment dependent." }
      ],
      interfaceContext: { state:"PARTIAL" },
      engineeringInputs: { state:"NOT_APPLICABLE" },
      proof: { required:false, state:"NOT_APPLICABLE", objects:[] },
      architecture: { state:"NOT_APPLICABLE" },
      physicalObjects: { state:"FACT", classes:["shipment","permit","licence","customs dossier","handoff"] },
      quantityDriver: { state:"OPEN", value:"shipment / controlled-equipment / permit occurrence" },
      requiredMto: { state:"NOT_APPLICABLE", quantity:null },
      bulk: { state:"NOT_APPLICABLE" },
      vendorOffer: { state:"PARTIAL", quantity:null },
      reconciliation: { state:"PARTIAL", disposition:null },
      workResource: { state:"WORKING" },
      documentQa: { state:"WORKING" },
      fatIfat: { state:"NOT_APPLICABLE" },
      logisticsRegulatory: { state:"OPEN" },
      siteReadiness: { state:"PARTIAL" },
      installPrecom: { state:"NOT_APPLICABLE" },
      satCommissioning: { state:"NOT_APPLICABLE" },
      handoverWarranty: { state:"NOT_APPLICABLE" },
      costScheduleRisk: { state:"PARTIAL", costValue:null, currency:"USD", costBasis:"Shipment / permit / admin / cash exposure" },
      commercialTreatment: { state:"WORKING", priceLine:"B2 / B8 as applicable" }
    }
  },
  {
    id: "CTRL-SPARE-001",
    object: "Spares / Tools / Consumables",
    system: "COMMON",
    source: "0550 priced-breakdown and technical spare/tool obligations",
    applicability: "ACTIVE BY PRICE SCHEDULE",
    driver: "Procurement class + required quantity basis",
    proof: "Requirement + OEM recommendation + engineering need",
    quantity: "Separate installed / commissioning / 2Y / capital / tool classes",
    workload: "Procurement + review + document / logistics as applicable",
    owner: "TBC per class",
    treatment: "Keep Base / C2 / C3 / tool treatment as separate commercial states",
    state: "QUANTITY / PRICE OPEN",
    next: "Never merge spare classes into installed quantity and never treat vendor recommendation as the project requirement.",
    control: {
      sourceEvidence: { state:"FACT", refs:["Priced Breakdown","MR/SPE spare obligations"] },
      requirement: { state:"FACT", value:"Provide required startup/commissioning, operation, capital and tool classes per project obligation." },
      fundamentalNeed: { state:"FACT", value:"Maintain commissioning readiness, operational continuity and maintainability." },
      constraints: [{ id:"SPARE-C-01", type:"TECHNICAL", state:"OPEN", value:"Final vendor spare recommendations / required class quantities not fully closed." }],
      interfaceContext: { state:"FACT" },
      engineeringInputs: { state:"PARTIAL" },
      proof: { required:false, state:"NOT_APPLICABLE", objects:[] },
      architecture: { state:"NOT_APPLICABLE" },
      physicalObjects: { state:"FACT", classes:["startup spare","commissioning spare","2Y spare","capital spare","special tool","consumable"] },
      quantityDriver: { state:"PARTIAL", value:"installed population + criticality + lifecycle class + OEM recommendation + project requirement" },
      requiredMto: { state:"TBC", quantity:null },
      bulk: { state:"NOT_APPLICABLE" },
      vendorOffer: { state:"PARTIAL", quantity:null },
      reconciliation: { state:"OPEN", disposition:null },
      workResource: { state:"WORKING" },
      documentQa: { state:"WORKING" },
      fatIfat: { state:"NOT_APPLICABLE" },
      logisticsRegulatory: { state:"WORKING" },
      siteReadiness: { state:"NOT_APPLICABLE" },
      installPrecom: { state:"NOT_APPLICABLE" },
      satCommissioning: { state:"NOT_APPLICABLE" },
      handoverWarranty: { state:"WORKING" },
      costScheduleRisk: { state:"WORKING", costValue:null, currency:"USD", costBasis:"Class-separated working allowance / vendor quote where available" },
      commercialTreatment: { state:"WORKING", priceLine:"B5/B6/C2/C3 as applicable" }
    }
  }
];
