INSERT INTO etm_equation_method_sources
(source_code,source_project,source_title,source_revision,source_type,reuse_policy,source_uri,status)
VALUES
('METH-0553-GEQ','PJ2608-0553','PJ2608-0553_MASTER_MATHEMATICAL_EQUATION_AI_CONTEXT','Rev04-DRAFT','CONTROLLED_MODEL',
 'Reuse equation form, model class, controls and research/standards pedigree only. Do not import 0553 quantities, crew, rates or commercial parameters.',
 'https://drive.google.com/file/d/1JA7D8WmHrzS81tIQg9wks1hObSqu3W1X/view','ACTIVE'),
('METH-0553-TPP','PJ2608-0553','PJ2608-0553_TPP_EPC_Equation_Model','Rev02.1-DRAFT','CONTROLLED_MODEL',
 'Reuse COMMON / GENERIC / PARTICULAR binding architecture. Rebind all project facts to PJ2608-0550.',
 'https://drive.google.com/file/d/1P-UoDiGJfWt8REdjot2LmXKMs7rWAM6l/view','ACTIVE'),
('METH-0553-VDRL','PJ2608-0553','PJ2608-0553_MR0002_DMR_VDRL_MATHEMATICAL_MODEL','Rev00','CONTROLLED_MODEL',
 'Reuse Q_issue versus Q_content separation, document workflow, revision and due-date mathematics. Do not import MR2 counts or document numbers.',
 'https://drive.google.com/file/d/14xg7ruStfEGU2tvWyoWQFMy69zhEWU2Y/view','ACTIVE'),
('METH-0541-HIST','PJ2607-0541','OMEGA 0541 historical bid / VDRS / campaign patterns',NULL,'HISTORICAL_REFERENCE',
 'Use only as historical workflow/calibration reference after verifying the exact 0541 source. Never import 0541 rates, quantities or scope as 0550 facts.',
 NULL,'ACTIVE')
ON DUPLICATE KEY UPDATE
 source_title=VALUES(source_title),source_revision=VALUES(source_revision),
 source_type=VALUES(source_type),reuse_policy=VALUES(reuse_policy),source_uri=VALUES(source_uri),status=VALUES(status);

INSERT INTO etm_equation_registry
(equation_code,equation_layer,equation_domain,equation_name,expression_text,model_class,evidence_basis,grounding_class,calibration_state,control_status,method_source,method_revision,control_note)
VALUES
('GEQ-001','COMMON','APPLICABILITY','Applicability','I_i = Applicable(Requirement, Scope, Phase, Context, Interface) ∈ {0,1}','STRUCTURAL_RULE','LOGIC_REVIEW','CONCEPTUAL_REFERENCE','N/A','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT','Particular requirements bind applicability; unknown input does not create a new equation.'),
('GEQ-002','COMMON','QUANTITY','Installed Quantity','Q_installed,e = Σ_f I[f,e] × q[f,e]','MATHEMATICAL_IDENTITY','DEFINITIONAL','IDENTITY_NO_CITATION_REQUIRED','N/A','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT',NULL),
('GEQ-004','COMMON','DRIVER','Activity Quantity Driver','Q_i = Driver(B_i, Context)','STRUCTURAL_RULE','MODEL_DEFINITION','CONCEPTUAL_REFERENCE','N/A','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT',NULL),
('GEQ-005','COMMON','RESOURCE','Role Man-hours','MH_i,r = I_i × Q_i × UMH_i,r × F_combined,i,r','PARAMETRIC_CER_CANDIDATE','PARTIAL_STRUCTURE_ONLY / CER_METHOD_CONCEPT','CALIBRATION_REQUIRED / CONCEPTUAL_REFERENCE','REQUIRED','CONTROLLED_WORKING_BASELINE / FACTOR_CONTROL_ADDED','METH-0553-GEQ','Rev04-DRAFT','Only non-overlapping calibrated/policy-supported factors may be combined; no universal hard-coded cap.'),
('GEQ-006','COMMON','SCHEDULE','Activity Duration','D_i,r(n) = MH_i,r / (n × H_day × η_i,r(n,Context)); parallel D_i = MAX_r(D_i,r(N_plan,i,r))','ESTABLISHED_METHOD / RESOURCE_CONSTRAINED','BASIC_RESOURCE_SCHEDULING + CONSTRAINT_AWARE_DURATION','DIRECT_METHOD_REFERENCE','PARAMETER_CALIBRATION','CONTROLLED_WORKING_BASELINE / RESOURCE_EFFECTIVENESS_ADDED','METH-0553-GEQ','Rev04-DRAFT','Crew effectiveness may vary with context.'),
('GEQ-007','COMMON','RESOURCE','Required / Feasible Headcount','N_req,i,r = MIN{n∈N+ : D_i,r(n) ≤ D_target}; N_plan,i,r = MIN(N_req,i,r, N_cap,i,r)','RESOURCE_FEASIBILITY_RULE','RESOURCE_CONSTRAINT_LOGIC','DIRECT_METHOD_REFERENCE','CAPACITY_AND_PRODUCTIVITY_INPUT','CONTROLLED_WORKING_BASELINE / PHYSICAL_CAP_ADDED','METH-0553-GEQ','Rev04-DRAFT','If required crew exceeds actual cap, schedule is infeasible rather than silently forced.'),
('GEQ-008','COMMON','COST','Regular Labor Cost','C_labor,i = Σ_r MH_i,r × Rate_r','ACCOUNTING_IDENTITY','DEFINITIONAL','IDENTITY_NO_CITATION_REQUIRED','RATE_LIBRARY','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT',NULL),
('GEQ-009','COMMON','DOCUMENT','Document Workflow MH','MH_doc = MH_author + MH_control + MH_review + MH_consolidate + MH_approve + MH_revise','ACCOUNTING_IDENTITY','WORK_BREAKDOWN_SUM','PROJECT_STANDARD','PRODUCTIVITY_CALIBRATION','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT','Technical authoring and document-control lifecycle must not be double-counted.'),
('GEQ-010','COMMON','DOCUMENT','Document Cycle Time','T_doc,realized = T_base + Σ_c I_rework,c × (T_revise,c + T_resubmit,c + T_response,c)','PROCESS_TIME_IDENTITY','DOCUMENT_REVIEW_LIFECYCLE','PROJECT_STANDARD','PROCESS_DATA / REVIEW_HISTORY','CONTROLLED_WORKING_BASELINE / LOOP_WIRING_ADDED','METH-0553-GEQ','Rev04-DRAFT','Expected-value form may be used only with supported historical probabilities.'),
('GEQ-011','COMMON','SCHEDULE','Event-relative Due Date','DueDate = EventDate + OffsetDays','MATHEMATICAL_IDENTITY','DEFINITIONAL','IDENTITY_NO_CITATION_REQUIRED','N/A','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT',NULL),
('GEQ-012','COMMON','PROCUREMENT_COST','Material / Landed Cost','C_material = Q_purchase × UnitPrice; C_landed = C_material + accessory + freight + duty + insurance','ACCOUNTING_IDENTITY','COST_BUILDUP','LAW_CONTRACT_POLICY','RATE_INPUTS','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT','Incoterm/contract defines component ownership.'),
('GEQ-013','COMMON','MOBILIZATION','Travel Cost','C_travel = Σ_l(Pax_l × Fare_l) + Σ_l OtherTransport_l','ACCOUNTING_IDENTITY','COST_BUILDUP','LAW_CONTRACT_POLICY','RATE_INPUTS','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT',NULL),
('GEQ-014','COMMON','MOBILIZATION','Hotel Rooms','Rooms = CEILING(Persons / Occupancy)','MATHEMATICAL_IDENTITY','CAPACITY_RELATION','IDENTITY_NO_CITATION_REQUIRED','POLICY_INPUT','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT',NULL),
('GEQ-015','COMMON','MOBILIZATION','Accommodation Cost','C_hotel = Rooms × Nights × Rate_room','ACCOUNTING_IDENTITY','DEFINITIONAL','IDENTITY_NO_CITATION_REQUIRED','RATE_INPUTS','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT',NULL),
('GEQ-016','COMMON','MOBILIZATION','Per-diem Cost','C_PD = Σ_r Persons_r × EligibleDays_r × Rate_PD,r','ACCOUNTING_IDENTITY','COST_BUILDUP','LAW_CONTRACT_POLICY','RATE_POLICY','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT',NULL),
('GEQ-017','COMMON','MOBILIZATION','Mobilization Cost','C_mob = Travel + Hotel + PerDiem + LocalTransport + Visa + Permit + Insurance + Other','ACCOUNTING_IDENTITY','COST_BUILDUP','LAW_CONTRACT_POLICY','RATE_INPUTS','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT',NULL),
('GEQ-018','COMMON','COST','Direct Activity Cost','C_activity,i = C_labor + C_OT + C_standby + C_mob + C_material + C_rental + C_subcontract + C_otherdirect','ACCOUNTING_IDENTITY','COST_ROLLUP','DIRECT_METHOD_REFERENCE / ACCOUNTING_STRUCTURE','N/A','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT',NULL),
('GEQ-019','COMMON','COST_OBJECT','Direct Equipment Cost','C_direct,e = C_landed,e + Σ_{i∈DirectActivities(e)} C_activity,i + C_assetlogistics,e','ACCOUNTING_IDENTITY','COST_ROLLUP','DIRECT_METHOD_REFERENCE / ACCOUNTING_STRUCTURE','ALLOCATION_RULES','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT',NULL),
('GEQ-020','COMMON','COMMON_COST','Common Project Cost','C_common = C_PM + C_DC + C_commonEng + C_commonMob + C_safety + C_commonTools + C_closeout + C_otherCommon','ACCOUNTING_IDENTITY','COST_ROLLUP','DIRECT_METHOD_REFERENCE / ACCOUNTING_STRUCTURE','OWNERSHIP_RULES','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT',NULL),
('GEQ-021','COMMON','TOTAL_COST','Total Project Cost','C_project = Σ_e C_direct,e + C_common','ACCOUNTING_IDENTITY','COST_ROLLUP','DIRECT_METHOD_REFERENCE / ACCOUNTING_STRUCTURE','N/A','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT','Canonical internal total; selling price is a separate commercial state.'),
('GEQ-022','COMMON','ALLOCATION','Fully Loaded Cost Allocation','C_loaded,e = C_direct,e + C_common × w_e; Σ_e w_e = 1','CAUSAL_ALLOCATION_METHOD','COST_ALLOCATION / ABC_CONCEPTUAL_BASIS','CONCEPTUAL_REFERENCE','ALLOCATION_POLICY','CONTROLLED_WORKING_BASELINE / DRIVER_BASIS_REQUIRED','METH-0553-GEQ','Rev04-DRAFT','Allocation driver must be causally defensible.'),
('GEQ-023','COMMON','EPC_STAGE','Stage Cost / Reconciliation','C_project,byStage = Σ_p C_stage,p','ACCOUNTING_IDENTITY / RECONCILIATION_VIEW','COST_ROLLUP','DIRECT_METHOD_REFERENCE / ACCOUNTING_STRUCTURE','N/A','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT','Reconciliation view must equal GEQ-021 when stage mapping is complete and non-duplicative.'),
('GEQ-024','GENERIC','DOCUMENT','Document Revision Workload','MH_doc,total = MH_initial + Σ_c(MH_review,c + MH_revise,c + MH_control,c) + MH_final','ACCOUNTING_IDENTITY','LIFECYCLE_WORK_BREAKDOWN','PROJECT_STANDARD','PRODUCTIVITY_CALIBRATION','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT',NULL),
('GEQ-025','GENERIC','INTEGRATION','Integration Workload','MH_integration,r = Σ_g I_g × UMH_interface,type(g),r × F_complexity,g × F_workmode,g,r','PARAMETRIC_CER_CANDIDATE / INTERFACE_GRAPH_DRIVER','SYSTEMS_INTERFACE_CONCEPT','CALIBRATION_REQUIRED / CONCEPTUAL_REFERENCE','REQUIRED','CONTROLLED_WORKING_BASELINE / NONLINEARITY_REFRAMED','METH-0553-GEQ','Rev04-DRAFT','Use actual controlled interface edges/types; do not force O(N²) from system count alone.'),
('GEQ-026','GENERIC','CONTEXT','Context-controlled Activity Set','Activities(P) = BaseActivities ∪ Triggered(Context) ∪ Required(ParticularRequirements)','STRUCTURAL_RULE','SET_THEORY_STRUCTURE','CONCEPTUAL_REFERENCE','N/A','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT',NULL),
('GEQ-027','COMMON','LABOR','Overtime Cost','C_OT,i,r = Σ_t MH_OT,i,r,t × Rate_r × M_OT,t','ACCOUNTING_IDENTITY','LABOR_COST_RULE','LAW_CONTRACT_POLICY','POLICY_AND_LEGAL_INPUT','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT',NULL),
('GEQ-028','COMMON','LABOR_COMMERCIAL','Standby Cost','C_standby,i = I_standby,i × Σ_r N_persons,r × StandbyDays_r × Rate_standby,r','ACCOUNTING_IDENTITY','LABOR_COST_RULE','LAW_CONTRACT_POLICY','RATE_POLICY','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT','Standby is never silently free.'),
('GEQ-031','COMMON','HAZARDOUS_AREA','Hazardous Area Protection Cost / Compliance Gate','I_ExReq = Applicable(...); I_ExCompat = CompatibilityGate(...); C_ExProtection = I_ExReq × (applicable Ex cost terms)','STRUCTURAL_RULE / ENGINEERING_COMPLIANCE_GATE','IEC_60079_FAMILY_CONCEPT + PROJECT_HAZARDOUS_AREA_REQUIREMENTS','DIRECT_COMPLIANCE_FAMILY_REFERENCE','RATE_AND_SCOPE_INPUT','CONTROLLED_WORKING_BASELINE / SCOPE_EXPANDED','METH-0553-GEQ','Rev04-DRAFT','Optional Ex accessories/install/inspection/cert terms require their own applicability gates.'),
('GEQ-032','GENERIC','PROCUREMENT','Procurement-class Quantity Conservation','Q_ordered,pseg = I_required × I_awarded × Q_required; Q_physical,pse = Σ_{g∈Gphysical} Q_ordered,pseg','MATHEMATICAL_IDENTITY','QUANTITY_CONSERVATION','IDENTITY_NO_CITATION_REQUIRED','N/A','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT',NULL),
('GEQ-033','GENERIC','COMMERCIAL','Commercial-treatment Line Cost','C_line,psj = I_required × I_awarded × Q_psj × P_psj; C_award = C_base + C_separate,awarded + C_option,exercised','ACCOUNTING_IDENTITY','COMMERCIAL_STATE_ROLLUP','DIRECT_METHOD_REFERENCE / ACCOUNTING_STRUCTURE','RATE_AND_AWARD_INPUT','CONTROLLED_WORKING_BASELINE','METH-0553-GEQ','Rev04-DRAFT',NULL)
ON DUPLICATE KEY UPDATE
 equation_layer=VALUES(equation_layer),equation_domain=VALUES(equation_domain),equation_name=VALUES(equation_name),
 expression_text=VALUES(expression_text),model_class=VALUES(model_class),evidence_basis=VALUES(evidence_basis),
 grounding_class=VALUES(grounding_class),calibration_state=VALUES(calibration_state),control_status=VALUES(control_status),
 method_source=VALUES(method_source),method_revision=VALUES(method_revision),control_note=VALUES(control_note);
