// Auto-recovered B1 cost lineage from controlled 0550 Rev04 model.
// Do not edit figures by hand; replace from a newer controlled derivation source when available.
export const B1_COST_LINEAGE = {
  "id": "B1-COST-LINEAGE-REV04-TO-REV10",
  "sourceFile": "PJ2608-0550_First-Principles_Resource-Protected_Budget_Model_Rev04_20261005.xlsx",
  "sourceDriveId": "1FsBuRPKCy1fEmw-4oLKbq-D4Hpq_Bs1t",
  "sourceDate": "05-Oct-2026",
  "currentAllowanceThb": 24000000,
  "recoveredBottomUpThb": 2936.8,
  "reconciliationGapThb": 23997063.2,
  "reconciliationState": "CURRENT_ALLOWANCE_NOT_FULLY_DERIVED",
  "interpretation": "The 24.0M THB Rev10 B1 value is a later management budgetary allowance. The latest fully traceable recovered bottom-up model found totals 11.155029M THB. The 12.844971M THB difference is not attributed to invented sub-lines; it remains an explicit reconciliation gap until a resource-loaded/current specialist basis closes it.",
  "summaries": [
    {
      "group": "SYSTEM_ENGINEERING",
      "rows": 0,
      "mh": 0,
      "eqDays": 0,
      "baseThb": 0,
      "internalCostThb": 0
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "rows": 25,
      "mh": 1718.75,
      "eqDays": 214.84375,
      "baseThb": 146.80000000000004,
      "internalCostThb": 18750
    },
    {
      "group": "VDRL_LIFECYCLE",
      "rows": 62,
      "mh": 277.2999999999999,
      "eqDays": 34.66249999999999,
      "baseThb": 2790,
      "internalCostThb": 24800
    },
    {
      "group": "COMMON_PROJECT",
      "rows": 0,
      "mh": 0,
      "eqDays": 0,
      "baseThb": 0,
      "internalCostThb": 0
    }
  ],
  "lineages": [
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "0",
      "token": "INT-001",
      "item": "INT-001 ↔ TEL-LAN · TEL-LAN-VCS",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 4,
      "role": "1",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 4,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · IP/LAN/Teams",
      "state": "11573.546875"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "1",
      "token": "INT-002",
      "item": "INT-002 ↔ TEL-LAN · TEL-PABX",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 6,
      "role": "1",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 6,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · IP/QoS/Management",
      "state": "17360.3203125"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "2",
      "token": "INT-003",
      "item": "INT-003 ↔ TEL-LAN · TEL-CCTV",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 6,
      "role": "1.2",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 7.199999999999999,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · IP/Video/Management",
      "state": "20832.384374999998"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "3",
      "token": "INT-004",
      "item": "INT-004 ↔ TEL-LAN · TEL-VSAT",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 6,
      "role": "1.2",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 7.199999999999999,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · IP/WAN",
      "state": "20832.384374999998"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "4",
      "token": "INT-005",
      "item": "INT-005 ↔ TEL-LAN · TEL-VSAT-KU",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 4,
      "role": "1",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 4,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · Internet/LAN Security",
      "state": "11573.546875"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "5",
      "token": "INT-006",
      "item": "INT-006 ↔ TEL-LAN · TEL-RADIO-DTRS",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 6,
      "role": "1.2",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 7.199999999999999,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · IP/RoIP/Management",
      "state": "20832.384374999998"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "6",
      "token": "INT-007",
      "item": "INT-007 ↔ TEL-LAN · TEL-RADIO-MARINE",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 4,
      "role": "1",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 4,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · IP Gateway/RoIP",
      "state": "11573.546875"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "7",
      "token": "INT-008",
      "item": "INT-008 ↔ TEL-LAN · TEL-RADIO-AERO",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 4,
      "role": "1",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 4,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · IP Gateway/RoIP",
      "state": "11573.546875"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "8",
      "token": "INT-009",
      "item": "INT-009 ↔ TEL-LAN · TEL-RADIO-SSB",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 4,
      "role": "1",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 4,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · IP Gateway/RoIP",
      "state": "11573.546875"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "9",
      "token": "INT-010",
      "item": "INT-010 ↔ TEL-LAN · TEL-DMR",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 6,
      "role": "1.2",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 7.199999999999999,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · IP Backhaul",
      "state": "20832.384374999998"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "10",
      "token": "INT-011",
      "item": "INT-011 ↔ TEL-LAN · TEL-MET",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 4,
      "role": "1",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 4,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · IP/Data Export",
      "state": "11573.546875"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "11",
      "token": "INT-012",
      "item": "INT-012 ↔ TEL-LAN · TEL-AIS",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 4,
      "role": "1",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 4,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · AIS Data/IP",
      "state": "11573.546875"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "12",
      "token": "INT-013",
      "item": "INT-013 ↔ TEL-LAN · TEL-NDB",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 4,
      "role": "1",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 4,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · Monitoring/IP",
      "state": "11573.546875"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "13",
      "token": "INT-014",
      "item": "INT-014 ↔ TEL-PABX · TEL-VSAT",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 6,
      "role": "1.2",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 7.199999999999999,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · Voice/SIP/WAN",
      "state": "20832.384374999998"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "14",
      "token": "INT-015",
      "item": "INT-015 ↔ TEL-RADIO-DTRS · TEL-VSAT",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 6,
      "role": "1.2",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 7.199999999999999,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · RoIP/WAN",
      "state": "20832.384374999998"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "15",
      "token": "INT-016",
      "item": "INT-016 ↔ TEL-PAGA · EXT-FGS",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 8,
      "role": "1.3",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 10.4,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · Alarm trigger / dry contact / protocol",
      "state": "30091.221875000003"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "16",
      "token": "INT-017",
      "item": "INT-017 ↔ TEL-PAGA · TEL-ES",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 4,
      "role": "1",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 4,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · BGM/priority interface",
      "state": "11573.546875"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "17",
      "token": "INT-018",
      "item": "INT-018 ↔ TEL-FO · TEL-LAN",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 6,
      "role": "1.2",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 7.199999999999999,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · Optical backbone",
      "state": "20832.384374999998"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "18",
      "token": "INT-019",
      "item": "INT-019 ↔ TEL-FO · TEL-CCTV",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 6,
      "role": "1.2",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 7.199999999999999,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · Optical transport",
      "state": "20832.384374999998"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "19",
      "token": "INT-020",
      "item": "INT-020 ↔ TEL-DMR · TEL-TELT",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 6,
      "role": "1.2",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 7.199999999999999,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · Antenna/mount/feeders",
      "state": "20832.384374999998"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "20",
      "token": "INT-021",
      "item": "INT-021 ↔ TEL-RADIO-DTRS · TEL-TELT",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 6,
      "role": "1.2",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 7.199999999999999,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · Antenna/mount/feeders",
      "state": "20832.384374999998"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "21",
      "token": "INT-022",
      "item": "INT-022 ↔ TEL-RADIO-MARINE · TEL-TELT",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 4,
      "role": "1",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 4,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · Antenna/mount/feeders",
      "state": "11573.546875"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "22",
      "token": "INT-023",
      "item": "INT-023 ↔ TEL-RADIO-AERO · TEL-TELT",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 4,
      "role": "1",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 4,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · Antenna/mount/feeders",
      "state": "11573.546875"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "23",
      "token": "INT-024",
      "item": "INT-024 ↔ TEL-RADIO-SSB · TEL-TELT",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 4,
      "role": "1",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 4,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · Antenna/earthing",
      "state": "11573.546875"
    },
    {
      "group": "INTERFACE_ENGINEERING",
      "id": "24",
      "token": "INT-025",
      "item": "INT-025 ↔ TEL-VSAT · EXT-OFFSHORE",
      "driverQty": 1,
      "driverUnit": "interface edge",
      "setupMh": 0,
      "umh": 1,
      "factor": 8,
      "role": "1.3",
      "rateUsdH": null,
      "mh": 68.75,
      "eqDays": 8.59375,
      "baseThb": 10.4,
      "internalThbH": null,
      "internalCostThb": 750,
      "source": "PRELIMINARY · SCADA/AIS/Voice transport",
      "state": "30091.221875000003"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "0",
      "token": "VDRL-001",
      "item": "TEL-LAN document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 14,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 63,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "119312.74687500001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "1",
      "token": "VDRL-002",
      "item": "TEL-LAN document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 9,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 33.300000000000004,
      "mh": 3.7,
      "eqDays": 0.4625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "63065.30906250001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "2",
      "token": "VDRL-003",
      "item": "TEL-LAN document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 7,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 31.5,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "59656.373437500006"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "3",
      "token": "VDRL-004",
      "item": "TEL-LAN-VCS document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 7,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 31.5,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "59656.373437500006"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "4",
      "token": "VDRL-005",
      "item": "TEL-LAN-VCS document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 5,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 18.5,
      "mh": 3.7,
      "eqDays": 0.4625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "35036.2828125"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "5",
      "token": "VDRL-006",
      "item": "TEL-LAN-VCS document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 4,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 18,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "34089.35625"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "6",
      "token": "VDRL-007",
      "item": "TEL-PABX document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 11,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 49.5,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "93745.7296875"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "7",
      "token": "VDRL-008",
      "item": "TEL-PABX document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 7,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 25.900000000000002,
      "mh": 3.7,
      "eqDays": 0.4625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "49050.79593750001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "8",
      "token": "VDRL-009",
      "item": "TEL-PABX document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 6,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 27,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "51134.034375"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "9",
      "token": "VDRL-010",
      "item": "TEL-IPP document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 8,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 36,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "68178.7125"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "10",
      "token": "VDRL-011",
      "item": "TEL-IPP document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 6,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 22.200000000000003,
      "mh": 3.7,
      "eqDays": 0.4625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "42043.53937500001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "11",
      "token": "VDRL-012",
      "item": "TEL-IPP document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 5,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 22.5,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "42611.69531250001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "12",
      "token": "VDRL-013",
      "item": "TEL-PAGA document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 15,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 67.5,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "127835.0859375"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "13",
      "token": "VDRL-014",
      "item": "TEL-PAGA document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 10,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 37,
      "mh": 3.7,
      "eqDays": 0.4625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "70072.565625"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "14",
      "token": "VDRL-015",
      "item": "TEL-PAGA document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 8,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 36,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "68178.7125"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "15",
      "token": "VDRL-016",
      "item": "TEL-CCTV document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 14,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 63,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "119312.74687500001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "16",
      "token": "VDRL-017",
      "item": "TEL-CCTV document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 10,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 37,
      "mh": 3.7,
      "eqDays": 0.4625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "70072.565625"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "17",
      "token": "VDRL-018",
      "item": "TEL-CCTV document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 8,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 36,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "68178.7125"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "18",
      "token": "VDRL-019",
      "item": "TEL-VSAT document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 13,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 58.5,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "110790.4078125"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "19",
      "token": "VDRL-020",
      "item": "TEL-VSAT document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 9,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 33.300000000000004,
      "mh": 3.7,
      "eqDays": 0.4625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "63065.30906250001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "20",
      "token": "VDRL-021",
      "item": "TEL-VSAT document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 7,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 31.5,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "59656.373437500006"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "21",
      "token": "VDRL-022",
      "item": "TEL-VSAT-KU document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 8,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 36,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "68178.7125"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "22",
      "token": "VDRL-023",
      "item": "TEL-VSAT-KU document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 6,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 22.200000000000003,
      "mh": 3.7,
      "eqDays": 0.4625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "42043.53937500001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "23",
      "token": "VDRL-024",
      "item": "TEL-VSAT-KU document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 5,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 22.5,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "42611.69531250001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "24",
      "token": "VDRL-025",
      "item": "TEL-RADIO-DTRS document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 13,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 58.5,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "110790.4078125"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "25",
      "token": "VDRL-026",
      "item": "TEL-RADIO-DTRS document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 9,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 33.300000000000004,
      "mh": 3.7,
      "eqDays": 0.4625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "63065.30906250001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "26",
      "token": "VDRL-027",
      "item": "TEL-RADIO-DTRS document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 7,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 31.5,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "59656.373437500006"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "27",
      "token": "VDRL-028",
      "item": "TEL-RADIO-MARINE document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 8,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 36,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "68178.7125"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "28",
      "token": "VDRL-029",
      "item": "TEL-RADIO-MARINE document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 6,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 22.200000000000003,
      "mh": 3.7,
      "eqDays": 0.4625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "42043.53937500001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "29",
      "token": "VDRL-030",
      "item": "TEL-RADIO-MARINE document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 5,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 22.5,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "42611.69531250001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "30",
      "token": "VDRL-031",
      "item": "TEL-RADIO-AERO document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 8,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 36,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "68178.7125"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "31",
      "token": "VDRL-032",
      "item": "TEL-RADIO-AERO document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 6,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 22.200000000000003,
      "mh": 3.7,
      "eqDays": 0.4625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "42043.53937500001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "32",
      "token": "VDRL-033",
      "item": "TEL-RADIO-AERO document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 5,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 22.5,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "42611.69531250001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "33",
      "token": "VDRL-034",
      "item": "TEL-RADIO-SSB document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 8,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 36,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "68178.7125"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "34",
      "token": "VDRL-035",
      "item": "TEL-RADIO-SSB document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 6,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 22.200000000000003,
      "mh": 3.7,
      "eqDays": 0.4625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "42043.53937500001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "35",
      "token": "VDRL-036",
      "item": "TEL-RADIO-SSB document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 5,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 22.5,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "42611.69531250001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "36",
      "token": "VDRL-037",
      "item": "TEL-DMR document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 13,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 58.5,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "110790.4078125"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "37",
      "token": "VDRL-038",
      "item": "TEL-DMR document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 9,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 33.300000000000004,
      "mh": 3.7,
      "eqDays": 0.4625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "63065.30906250001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "38",
      "token": "VDRL-039",
      "item": "TEL-DMR document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 7,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 31.5,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "59656.373437500006"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "39",
      "token": "VDRL-040",
      "item": "TEL-ES document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 7,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 31.5,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "59656.373437500006"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "40",
      "token": "VDRL-041",
      "item": "TEL-ES document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 5,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 18.5,
      "mh": 3.7,
      "eqDays": 0.4625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "35036.2828125"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "41",
      "token": "VDRL-042",
      "item": "TEL-ES document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 4,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 18,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "34089.35625"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "42",
      "token": "VDRL-043",
      "item": "TEL-FO document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 10,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 45,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "85223.39062500001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "43",
      "token": "VDRL-044",
      "item": "TEL-FO document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 8,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 29.6,
      "mh": 3.7,
      "eqDays": 0.4625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "56058.052500000005"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "44",
      "token": "VDRL-045",
      "item": "TEL-FO document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 6,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 27,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "51134.034375"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "45",
      "token": "VDRL-046",
      "item": "TEL-TELT document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 10,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 45,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "85223.39062500001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "46",
      "token": "VDRL-047",
      "item": "TEL-TELT document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 8,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 29.6,
      "mh": 3.7,
      "eqDays": 0.4625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "56058.052500000005"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "47",
      "token": "VDRL-048",
      "item": "TEL-TELT document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 5,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 22.5,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "42611.69531250001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "48",
      "token": "VDRL-049",
      "item": "TEL-MET document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 8,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 36,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "68178.7125"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "49",
      "token": "VDRL-050",
      "item": "TEL-MET document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 6,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 22.200000000000003,
      "mh": 3.7,
      "eqDays": 0.4625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "42043.53937500001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "50",
      "token": "VDRL-051",
      "item": "TEL-MET document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 5,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 22.5,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "42611.69531250001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "51",
      "token": "VDRL-052",
      "item": "TEL-NDB document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 12,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 54,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "102268.06875"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "52",
      "token": "VDRL-053",
      "item": "TEL-NDB document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 8,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 29.6,
      "mh": 3.7,
      "eqDays": 0.4625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "56058.052500000005"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "53",
      "token": "VDRL-054",
      "item": "TEL-NDB document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 6,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 27,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "51134.034375"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "54",
      "token": "VDRL-055",
      "item": "TEL-AIS document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 6,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 27,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "51134.034375"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "55",
      "token": "VDRL-056",
      "item": "TEL-AIS document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 5,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 18.5,
      "mh": 3.7,
      "eqDays": 0.4625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "35036.2828125"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "56",
      "token": "VDRL-057",
      "item": "TEL-AIS document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 4,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 18,
      "mh": 4.5,
      "eqDays": 0.5625,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "34089.35625"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "57",
      "token": "VDRL-C01",
      "item": "COMMON document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 18,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 72,
      "mh": 4,
      "eqDays": 0.5,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "DUMMY/PARAMETRIC",
      "state": "136357.425"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "58",
      "token": "VDRL-C02",
      "item": "COMMON document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 18,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 36,
      "mh": 2,
      "eqDays": 0.25,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "DUMMY/PARAMETRIC",
      "state": "68178.7125"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "59",
      "token": "VDRL-C03",
      "item": "COMMON document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 18,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 36,
      "mh": 2,
      "eqDays": 0.25,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "DUMMY/PARAMETRIC",
      "state": "68178.7125"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "60",
      "token": "VDRL-C04",
      "item": "COMMON document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 14,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 56,
      "mh": 4,
      "eqDays": 0.5,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "106055.77500000001"
    },
    {
      "group": "VDRL_LIFECYCLE",
      "id": "61",
      "token": "VDRL-C05",
      "item": "COMMON document lifecycle",
      "driverQty": null,
      "driverUnit": "effective docs",
      "setupMh": 0,
      "umh": 1,
      "factor": 1,
      "role": "BLENDED",
      "rateUsdH": 24,
      "mh": 24,
      "eqDays": 3,
      "baseThb": 45,
      "internalThbH": null,
      "internalCostThb": 400,
      "source": "PARAMETRIC",
      "state": "45452.475000000006"
    }
  ]
};
