SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS etm_bid_form_lines (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 bid_package_id BIGINT UNSIGNED NOT NULL,
 control_id VARCHAR(128) NOT NULL,
 source_group VARCHAR(96) NULL,
 source_ref VARCHAR(255) NOT NULL,
 requirement_text TEXT NOT NULL,
 bidder_response TEXT NULL,
 response_ref VARCHAR(255) NULL,
 response_status VARCHAR(64) NOT NULL DEFAULT 'OPEN',
 deviation_route ENUM('NONE','TECHNICAL','COMMERCIAL','CLARIFICATION','OPTION','EXCLUSION','TBC') NOT NULL DEFAULT 'TBC',
 internal_note TEXT NULL,
 customer_note TEXT NULL,
 is_current TINYINT(1) NOT NULL DEFAULT 1,
 metadata_json JSON NULL,
 UNIQUE KEY uq_bid_form_line(bid_package_id,control_id),
 FOREIGN KEY(bid_package_id) REFERENCES etm_bid_packages(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS etm_vdrl_occurrences (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 project_id BIGINT UNSIGNED NOT NULL,
 system_id BIGINT UNSIGNED NULL,
 vdrl_item_id BIGINT UNSIGNED NULL,
 occurrence_code VARCHAR(128) NOT NULL,
 dossier_group VARCHAR(128) NULL,
 deliverable_title VARCHAR(500) NOT NULL,
 source_authority VARCHAR(255) NOT NULL,
 source_row_ref VARCHAR(128) NULL,
 source_sdrl_code VARCHAR(64) NULL,
 source_mapping_status ENUM('VERIFIED','TITLE_VERIFIED_CODE_TBC','TBC','NOT_APPLICABLE') NOT NULL DEFAULT 'TBC',
 with_bid_status ENUM('YES','NO','VERIFY','NOT_APPLICABLE') NOT NULL DEFAULT 'VERIFY',
 bidding_required TINYINT(1) NULL,
 execution_required TINYINT(1) NULL,
 approval_information VARCHAR(32) NULL,
 owner_basis VARCHAR(128) NULL,
 owner_basis_class ENUM('SOURCE','WORKING_MODEL','TBC') NOT NULL DEFAULT 'TBC',
 status ENUM('NOT_STARTED','IN_PROGRESS','PARTIAL','READY','BLOCKED','HOLD','NA') NOT NULL DEFAULT 'NOT_STARTED',
 assignee VARCHAR(128) NULL,
 evidence_ref TEXT NULL,
 next_action TEXT NULL,
 generator_profile VARCHAR(128) NULL,
 quantity_driver DECIMAL(24,8) NULL,
 quantity_unit VARCHAR(32) NULL,
 umh DECIMAL(24,8) NULL,
 calculated_mh DECIMAL(24,8) NULL,
 metadata_json JSON NULL,
 UNIQUE KEY uq_vdrl_occurrence(project_id,occurrence_code),
 FOREIGN KEY(project_id) REFERENCES etm_projects(id),
 FOREIGN KEY(system_id) REFERENCES etm_systems(id),
 FOREIGN KEY(vdrl_item_id) REFERENCES etm_vdrl_items(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS etm_document_generation_jobs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 project_id BIGINT UNSIGNED NOT NULL,
 vdrl_occurrence_id BIGINT UNSIGNED NULL,
 job_code VARCHAR(128) NOT NULL,
 generator_profile VARCHAR(128) NOT NULL,
 target_format ENUM('DOCX','XLSX','PDF','HTML','JSON') NOT NULL,
 template_code VARCHAR(96) NULL,
 input_snapshot_json JSON NULL,
 output_storage_uri TEXT NULL,
 generation_status ENUM('DRAFT','READY','GENERATING','GENERATED','FAILED','SUPERSEDED') NOT NULL DEFAULT 'DRAFT',
 internal_review_status VARCHAR(64) NULL,
 customer_preview_status VARCHAR(64) NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 metadata_json JSON NULL,
 UNIQUE KEY uq_doc_gen_job(project_id,job_code),
 FOREIGN KEY(project_id) REFERENCES etm_projects(id),
 FOREIGN KEY(vdrl_occurrence_id) REFERENCES etm_vdrl_occurrences(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
