// PJ2608-0553 vendor evidence is particular to this bid.
// A source quotation is not an approved supplier or customer selling price.
export const VENDOR_0553_SOURCES = [
 {id:"V-SCADA-NEXTG",mr:"MR-0001",supplier:"NextG / Aviat",type:"RFQ/QUOTATION_FOLDER",document:"MR-502 Subscriber Radio, ODU / IDU / antenna",url:"https://drive.google.com/drive/folders/1SRLpZVlx7qpT7TiXAm0mSwPAijF5ySCe",status:"SOURCE_INDEXED",next:"Extract actual quote revision and line items; compare MTO Rev04 and link-budget CAL"},
 {id:"V-SCADA-CISCO",mr:"MR-0001",supplier:"VST ECS / Cisco",type:"QUOTATION_FOLDER",document:"LAN-502-001 Layer3 Switch",url:"https://drive.google.com/drive/folders/1s6BMmqdd2sswa3n3o7MP0Eba4oBKsI14",status:"SOURCE_INDEXED",next:"Validate switch SKU, licence, input power and full-set lead time"},
 {id:"V-SCADA-INNOVA",mr:"MR-0001",supplier:"INNOVA Corporation",type:"HISTORICAL_QUOTATION_2024_PROVISIONAL_BUDGET",document:"QA24-0604 / QA24-0605 / QA24-0606 — CAT6A, RJ45, glands, adapter",url:"https://drive.google.com/drive/folders/1aIuZenXjmKabdCGt4nR8WWA8morWioUX",status:"2024_PROVISIONAL_BUDGET_REQUOTE_PENDING",next:"Retain original quote lines, currency THB and N/A price; verify scope and quantity; not a current accepted vendor cost"},
 {id:"V-SCADA-OTHER",mr:"MR-0001",supplier:"Multiple / unconfirmed",type:"SOURCE_GROUP",document:"SCADA accessories / bulk / enclosure / surge / DATO",url:"https://drive.google.com/drive/folders/1lCOGxQlIHsY7q5rJaNkms7ZBIVjO9Bs5",status:"SOURCE_INDEXED",next:"Separate quotations from RFQs and datasheets; no unsupported unit rate"},
 {id:"V-RFI-LNA",mr:"MR-0001",supplier:"RFI / unconfirmed",type:"DATASHEET_ONLY",document:"Low Noise Amplifier RX3852-2002-11",url:"https://drive.google.com/file/d/1dAnYkC2r2hyYEgUuN-xA0xAvq-zG2iTA/view",status:"CANDIDATE_NOT_PRICED",next:"Confirm actual system applicability, frequency, gain, power and quotation"},
 {id:"V-MGW-P26-058",mr:"MULTI",supplier:"MGW Technologies Pte Ltd",type:"QUOTATION",document:"P26-058 — UHF BDA / RACON / Ex IP Phone / services",url:"https://drive.google.com/file/d/1qR4fuRXnRbHI2hgj8BB9T1dztZTWiINc/view",revision:"21-Sep-2026",currency:"USD",quotedTotal:273519,status:"QUOTED_MULTISYSTEM_UNRECONCILED",next:"Do not map full total to one MR. Verify brands, technical compliance, itemized scope, Ex Works Nantong, payment and warranty"},
 {id:"V-MGW-DMR-ANT",mr:"MR-0002",supplier:"MGW / component suppliers",type:"SUPPLIER_FOLDER",document:"RAD-508 / ANT-508-001 / ANT-508-002",url:"https://drive.google.com/drive/folders/1VrECsHvt2K9gxamr4pGMxMY3ypTeNq9v",status:"SOURCE_INDEXED",next:"Match antenna models and frequency/license rules to MTO and TC before selection"},
 {id:"V-TPH-GAITRONICS",mr:"MR-0003",supplier:"Gai-Tronics / e2S",type:"SUPPLIER_FOLDER",document:"Ex IP Phone and Sounder via Exion Thai",url:"https://drive.google.com/drive/folders/18i3LXAkcThSA7YHk6BLOuf-5qGtD9Xax",status:"CANDIDATE",next:"Extract offer and Ex certificate; compare phone, JB, horn/beacon, accessories"},
 {id:"V-TPH-JR",mr:"MR-0003",supplier:"J&R / MGW",type:"SUPPLIER_FOLDER",document:"Ex IP Phone, JB and sounder alternative",url:"https://drive.google.com/drive/folders/1OAkufAZPQvwQHSe9wJdQ2F3D870uzQ3d",status:"CANDIDATE",next:"Compare JREX106-SIP and grouped equipment/accessories to MR0003"},
 {id:"V-RACON-ORGA-2026",mr:"MR-0004",supplier:"MDS / Orga",type:"QUOTATION",document:"QTORG2609244 — SeaBeacon-2 System 6 Ex",url:"https://drive.google.com/file/d/1JRZ-Ex0gHg120fwpbfmYJEuhTzU4EJva/view",revision:"22-Sep-2026",status:"QUOTED_REVIEW_REQUIRED",next:"Extract complete price page/terms and quantity configuration; compare MGW RACON and exact MR"},
 {id:"V-RACON-ORGA-AUTH",mr:"MR-0004",supplier:"Orga",type:"AUTHORIZATION_CANDIDATE",document:"Orga Authorization Letter_Update.pdf",url:"https://drive.google.com/file/d/1Wlrw2XGZcN1-YDYBcvQZBA9Pe4m3fYz0/view",status:"VERIFY_DOCUMENT",next:"Verify authorized bidder entity, scope, signature and expiration"}
];
